import { html } from "yandom";

const Playground = () => {
    return html.$([
        html.section({ id: 'playground', class: "max-w-4xl mx-auto px-6 py-20 flex flex-col gap-16 mb-20" }, [
            html.div({ class: "flex flex-col gap-3" }, [
                html.span({ class: "text-comment" }, ["// playgrounds"]),
                html.h1({ class: "text-5xl font-black tracking-tighter text-white" }, ["Games you can play with"]),
                html.p({ class: "text-zinc-500 text-sm" }, [
                    "Various simple in web games you can play because why not?"
                ]),
            ]),

            html.canvas({ id: 'bg', width: '800', height: '530' }),

            html.canvas({ id: 'snake', width: '800', height: '530' }),
            
            html.script([
                "(() => {",
                "const cvs = document.getElementById('bg');",
                "const ctx = cvs.getContext('2d');",
                "const W = cvs.width, H = cvs.height;",
                "const PIPE_W = 52, GAP = 145, PIPE_SPEED = 2.2;",
                "const GRAVITY = 0.38, FLAP = -7.2, BIRD_R = 14;",
                "let bird, pipes, score, frame, state;",
                "function reset() { bird = { x: 90, y: H / 2, vy: 0 }; pipes = []; score = 0; frame = 0; state = 'idle'; }",
                "reset();",
                "function spawnPipe() { const top = 80 + Math.random() * (H - GAP - 160); pipes.push({ x: W, top, scored: false }); }",
                "function flap() { if (state === 'idle') { state = 'play'; spawnPipe(); } if (state === 'play') bird.vy = FLAP; if (state === 'dead') reset(); }",
                "cvs.addEventListener('click', flap);",
                "document.addEventListener('keydown', e => { if (e.code === 'Space') { e.preventDefault(); flap(); } });",
                "function hitTest() { if (bird.y + BIRD_R > H - 48 || bird.y - BIRD_R < 0) return true; for (const p of pipes) { if (bird.x + BIRD_R > p.x + 4 && bird.x - BIRD_R < p.x + PIPE_W - 4) { if (bird.y - BIRD_R < p.top || bird.y + BIRD_R > p.top + GAP) return true; } } return false; }",
                "function drawSky() { const g = ctx.createLinearGradient(0,0,0,H); g.addColorStop(0,'#5ec4f0'); g.addColorStop(1,'#a8def7'); ctx.fillStyle = g; ctx.fillRect(0,0,W,H); }",
                "function drawGround() { ctx.fillStyle='#c8a850'; ctx.fillRect(0,H-40,W,40); ctx.fillStyle='#5db85a'; ctx.fillRect(0,H-48,W,12); }",
                "function drawPipe(x, top) { const bot = top + GAP, capH = 18, capW = PIPE_W + 8; ctx.fillStyle='#4db34a'; ctx.fillRect(x,0,PIPE_W,top); ctx.fillRect(x,bot,PIPE_W,H-bot-40); ctx.fillStyle='#5fc05b'; ctx.fillRect(x-4,top-capH,capW,capH); ctx.fillRect(x-4,bot,capW,capH); }",
                "function drawBird(x, y, vy) { const tilt = Math.max(-0.5, Math.min(0.8, vy * 0.07)); ctx.save(); ctx.translate(x,y); ctx.rotate(tilt); ctx.fillStyle='#f5d800'; ctx.beginPath(); ctx.ellipse(0,0,BIRD_R,BIRD_R-2,0,0,Math.PI*2); ctx.fill(); ctx.fillStyle='#fff'; ctx.beginPath(); ctx.ellipse(5,-5,6,5,0.2,0,Math.PI*2); ctx.fill(); ctx.fillStyle='#222'; ctx.beginPath(); ctx.ellipse(7,-5.5,3,3,0,0,Math.PI*2); ctx.fill(); ctx.fillStyle='#f07820'; ctx.beginPath(); ctx.moveTo(10,-1); ctx.lineTo(18,1); ctx.lineTo(10,3); ctx.closePath(); ctx.fill(); ctx.restore(); }",
                "function loop() { requestAnimationFrame(loop); frame++; if (state === 'play') { bird.vy += GRAVITY; bird.y += bird.vy; pipes.forEach(p => { p.x -= PIPE_SPEED; if (!p.scored && p.x + PIPE_W < bird.x) { p.scored = true; score++; } }); pipes = pipes.filter(p => p.x > -PIPE_W - 10); if (frame % 120 === 0) spawnPipe(); if (hitTest()) state = 'dead'; } drawSky(); pipes.forEach(p => drawPipe(p.x, p.top)); drawGround(); drawBird(bird.x, bird.y, bird.vy); ctx.fillStyle='#fff'; ctx.strokeStyle='#333'; ctx.lineWidth=3; ctx.font='500 28px sans-serif'; ctx.textAlign='center'; if (state !== 'idle') { ctx.strokeText(score,W/2,52); ctx.fillText(score,W/2,52); } if (state === 'idle') { ctx.fillStyle='rgba(0,0,0,0.4)'; ctx.fillRect(W/2-120,H/2-56,240,80); ctx.fillStyle='#fff'; ctx.font='500 22px sans-serif'; ctx.fillText('Flappy Bird',W/2,H/2-24); ctx.font='400 15px sans-serif'; ctx.fillText('tap or space to start',W/2,H/2+10); } if (state === 'dead') { ctx.fillStyle='rgba(0,0,0,0.4)'; ctx.fillRect(W/2-110,H/2-64,220,100); ctx.fillStyle='#fff'; ctx.font='500 24px sans-serif'; ctx.fillText('game over',W/2,H/2-26); ctx.font='400 15px sans-serif'; ctx.fillText('score: '+score,W/2,H/2+4); ctx.fillText('tap to restart',W/2,H/2+26); } }",
                "loop();",
                "})();",

                "(() => {",
                "const cvs = document.getElementById('snake');",
                "const ctx = cvs.getContext('2d');",
                "const W = cvs.width, H = cvs.height;",
                "const CELL = 20, COLS = W / CELL, ROWS = H / CELL;",
                "const TICK = 100;",

                "let snake, dir, next, food, score, best, state, last;",
                "best = localStorage.getItem('ronelPortfolio_snake') || 0;",

                "function randFood(s) {",
                "  let f;",
                "  do { f = { x: Math.floor(Math.random()*COLS), y: Math.floor(Math.random()*ROWS) }; }",
                "  while (s.some(p => p.x===f.x && p.y===f.y));",
                "  return f;",
                "}",

                "function reset() {",
                "  const mx = Math.floor(COLS/2), my = Math.floor(ROWS/2);",
                "  snake = [{x:mx,y:my},{x:mx-1,y:my},{x:mx-2,y:my}];",
                "  dir = {x:1,y:0}; next = {x:1,y:0};",
                "  food = randFood(snake);",
                "  score = 0; state = 'idle'; last = 0;",
                "}",
                "reset();",

                "const KEYS = { ArrowUp:{x:0,y:-1}, ArrowDown:{x:0,y:1}, ArrowLeft:{x:-1,y:0}, ArrowRight:{x:1,y:0}, w:{x:0,y:-1}, s:{x:0,y:1}, a:{x:-1,y:0}, d:{x:1,y:0} };",
                "document.addEventListener('keydown', e => {",
                "  if (state === 'dead') { reset(); return; }",
                "  const d = KEYS[e.key];",
                "  if (!d) return;",
                "  if (d.x === -dir.x && d.y === -dir.y) return;",
                "  if (['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)) e.preventDefault();",
                "  if (state === 'idle') state = 'play';",
                "  next = d;",
                "});",
                "cvs.addEventListener('click', () => { if (state === 'idle' || state === 'dead') reset(); });",

                "function drawBg() {",
                "  ctx.fillStyle = '#0f0f14';",
                "  ctx.fillRect(0, 0, W, H);",
                "  ctx.strokeStyle = 'rgba(255,255,255,0.03)';",
                "  ctx.lineWidth = 0.5;",
                "  for (let x=0;x<=W;x+=CELL) { ctx.beginPath(); ctx.moveTo(x,0); ctx.lineTo(x,H); ctx.stroke(); }",
                "  for (let y=0;y<=H;y+=CELL) { ctx.beginPath(); ctx.moveTo(0,y); ctx.lineTo(W,y); ctx.stroke(); }",
                "}",

                "function drawSnake() {",
                "  snake.forEach((p, i) => {",
                "    const t = i / snake.length;",
                "    const r = Math.round(100 + (139-100)*t), g = Math.round(220 + (195-220)*t), b = Math.round(130 + (100-130)*t);",
                "    ctx.fillStyle = i===0 ? '#a78bfa' : `rgb(${r},${g},${b})`;",
                "    const pad = i===0 ? 1 : 2;",
                "    ctx.beginPath();",
                "    ctx.roundRect(p.x*CELL+pad, p.y*CELL+pad, CELL-pad*2, CELL-pad*2, i===0?6:4);",
                "    ctx.fill();",
                "    if (i===0) {",
                "      ctx.fillStyle='#fff';",
                "      const ex = dir.x===0?3:dir.x>0?12:2, ey = dir.y===0?3:dir.y>0?12:2;",
                "      ctx.beginPath(); ctx.arc(p.x*CELL+ex, p.y*CELL+ey, 2.5, 0, Math.PI*2); ctx.fill();",
                "      ctx.beginPath(); ctx.arc(p.x*CELL+(CELL-ex), p.y*CELL+ey, 2.5, 0, Math.PI*2); ctx.fill();",
                "    }",
                "  });",
                "}",

                "function drawFood() {",
                "  const cx = food.x*CELL+CELL/2, cy = food.y*CELL+CELL/2, r = CELL/2-3;",
                "  ctx.fillStyle = '#f87171';",
                "  ctx.beginPath(); ctx.arc(cx, cy, r, 0, Math.PI*2); ctx.fill();",
                "  ctx.fillStyle = '#4ade80';",
                "  ctx.fillRect(cx, cy-r-3, 2.5, 5);",
                "}",

                "function drawHUD() {",
                "  ctx.font = '500 14px monospace'; ctx.textAlign = 'left';",
                "  ctx.fillStyle = 'rgba(255,255,255,0.3)'; ctx.fillText('SCORE', 16, 24);",
                "  ctx.fillStyle = '#a78bfa'; ctx.font = '500 22px monospace'; ctx.fillText(score, 16, 46);",
                "  ctx.font = '500 14px monospace'; ctx.textAlign = 'right';",
                "  ctx.fillStyle = 'rgba(255,255,255,0.3)'; ctx.fillText('BEST', W-16, 24);",
                "  ctx.fillStyle = 'rgba(255,255,255,0.5)'; ctx.font = '500 22px monospace'; ctx.fillText(best, W-16, 46);",
                "}",

                "function overlay(title, sub) {",
                "  ctx.fillStyle = 'rgba(0,0,0,0.55)';",
                "  ctx.fillRect(W/2-140, H/2-60, 280, 96);",
                "  ctx.fillStyle = '#fff'; ctx.font = '500 22px monospace'; ctx.textAlign='center';",
                "  ctx.fillText(title, W/2, H/2-22);",
                "  ctx.fillStyle='rgba(255,255,255,0.5)'; ctx.font='400 14px monospace';",
                "  ctx.fillText(sub, W/2, H/2+6);",
                "}",

                "function loop(ts) {",
                "  requestAnimationFrame(loop);",
                "  drawBg();",
                "  if (state === 'play') {",
                "    if (ts - last >= TICK) {",
                "      last = ts;",
                "      dir = next;",
                "      const head = { x: snake[0].x + dir.x, y: snake[0].y + dir.y };",
                "      if (head.x < 0 || head.x >= COLS || head.y < 0 || head.y >= ROWS || snake.some(p=>p.x===head.x&&p.y===head.y)) {",
                "        state = 'dead'; if (score > best) best = score, localStorage.setItem('ronelPortfolio_snake', score);",
                "      } else {",
                "        snake.unshift(head);",
                "        if (head.x===food.x && head.y===food.y) { score++; food=randFood(snake); }",
                "        else snake.pop();",
                "      }",
                "    }",
                "  }",
                "  drawFood();",
                "  drawSnake();",
                "  drawHUD();",
                "  if (state==='idle') overlay('Snake', 'arrow keys / wasd to start');",
                "  if (state==='dead') overlay('game over  //  '+score, 'press any key to restart');",
                "}",
                "requestAnimationFrame(loop);",
                "})();"
            ]),
        ]),
    ]);
};

export default Playground;